package com.taller.portal.repository;
import com.taller.portal.dto.AdministracionClienteDtos.*; import com.taller.portal.model.Cliente; import java.time.LocalDate; import java.util.*; import org.springframework.data.domain.*; import org.springframework.data.jpa.repository.*; import org.springframework.data.repository.query.Param;
/** Repositorio de clientes: cada lectura administrativa recibe taller obligatorio. */
public interface ClienteRepository extends JpaRepository<Cliente,Long>{
 Optional<Cliente> findByIdempotencyKey(String key);
 boolean existsByEmailOrTelefonoPersonalOrTelefonoTrabajoOrNombreCompletoAndFechaNacimiento(String email,String personal,String trabajo,String nombre,LocalDate fecha);
 @Query("select (count(c)>0) from Cliente c where c.id<>:id and (c.email=:email or c.telefonoPersonal=:personal or c.telefonoTrabajo=:trabajo or (c.nombreCompleto=:nombre and c.fechaNacimiento=:fecha))") boolean duplicadoExcluyendo(@Param("id") Long id,@Param("email") String email,@Param("personal") String personal,@Param("trabajo") String trabajo,@Param("nombre") String nombre,@Param("fecha") LocalDate fecha);
 @Query("select new com.taller.portal.dto.AdministracionClienteDtos$Resumen(c.id,c.nombreCompleto,c.telefonoPersonal,c.email,c.municipio,c.taller.id,c.taller.nombre,c.estatus) from Cliente c where c.taller.id=:tallerId and (lower(c.nombreCompleto) like :patron escape '!' or lower(c.telefonoPersonal) like :patron escape '!' or lower(c.email) like :patron escape '!')") Page<Resumen> consultarPorTaller(@Param("tallerId") Long tallerId,@Param("patron") String patron,Pageable pagina);
 @Query("select new com.taller.portal.dto.AdministracionClienteDtos$Detalle(c.id,c.nombreCompleto,c.contactoAlternativo,c.edad,c.fechaNacimiento,c.telefonoPersonal,c.telefonoTrabajo,c.email,c.emailTrabajo,c.calle,c.colonia,c.municipio,c.estado,c.codigoPostal,c.taller.id,c.taller.nombre,c.estatus) from Cliente c where c.id=:id and c.taller.id=:tallerId") Optional<Detalle> detallePorTaller(@Param("id") Long id,@Param("tallerId") Long tallerId);
 @Query("select c from Cliente c where c.id=:id and c.taller.id=:tallerId") Optional<Cliente> entidadPorTaller(@Param("id") Long id,@Param("tallerId") Long tallerId);
 @Query("select c.fotografiaRuta from Cliente c where c.id=:id and c.taller.id=:tallerId") Optional<String> rutaFotoPorTaller(@Param("id") Long id,@Param("tallerId") Long tallerId);
}
