package com.taller.portal.service;

import com.taller.portal.dto.AdministracionClienteDtos;
import com.taller.portal.dto.ClienteConsultaDtos;
import com.taller.portal.dto.ClienteDtos.*;
import com.taller.portal.model.*;
import com.taller.portal.repository.*;
import java.awt.image.BufferedImage; import java.io.*; import java.nio.file.*; import java.time.*; import java.util.*;
import javax.imageio.ImageIO;
import org.springframework.data.domain.*; import org.springframework.http.HttpStatus; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile; import org.springframework.web.server.ResponseStatusException;

/** Fachada única de clientes: valida, autoriza y aplica alcance por taller. */
@Service public class ClienteRegistrationFacade {
 private final ClienteRepository clientes; private final TallerRepository talleres; private final UserRepository usuarios; private final Path uploads=Paths.get("uploads","clientes");
 /** @param clientes acceso a clientes @param talleres acceso a alcance @param usuarios relación de recepción-taller. */
 public ClienteRegistrationFacade(ClienteRepository clientes,TallerRepository talleres,UserRepository usuarios){this.clientes=clientes;this.talleres=talleres;this.usuarios=usuarios;}
 /** Registra en el taller permitido e impide repetir clave idempotente. */
 @Transactional public Respuesta registrar(Registro d,MultipartFile foto,String key,Authentication a)throws IOException{
  autorizar(a); if(key==null||key.isBlank())throw new IllegalArgumentException("Idempotency-Key es obligatorio"); var previo=clientes.findByIdempotencyKey(key); if(previo.isPresent())return new Respuesta(previo.get().id,"Cliente Registrado");
  Taller t=tallerPermitido(d.tallerId(),a); validar(d,foto,true); duplicado(null,d); Cliente c=new Cliente(); aplicar(c,d,t); c.fotografiaRuta=guardarFoto(foto); c.idempotencyKey=key; clientes.save(c); return new Respuesta(c.id,"Cliente Registrado");
 }
 /** Lista clientes por taller con máximo diez, búsqueda y orden de lista blanca. */
 @Transactional(readOnly=true) public AdministracionClienteDtos.Pagina consultar(int pagina,int tamanio,String texto,Long tallerId,String orden,String direccion,Authentication a){
  Taller t=tallerPermitido(tallerId,a); if(pagina<0||pagina>100000)throw new IllegalArgumentException("Página inválida"); int limite=Math.min(Math.max(tamanio,1),10);
  Set<String> permitidas=Set.of("nombreCompleto","estatus","taller"); if(orden!=null&&!orden.isBlank()&&!permitidas.contains(orden))throw new IllegalArgumentException("Columna de orden inválida"); String campo=orden==null||orden.isBlank()?"nombreCompleto":orden;
  Sort.Direction dir="desc".equalsIgnoreCase(direccion)?Sort.Direction.DESC:Sort.Direction.ASC; String patron="%"+busqueda(texto)+"%"; var r=clientes.consultarPorTaller(t.id,patron,PageRequest.of(pagina,limite,Sort.by(dir,campo.equals("taller")?"taller.nombre":campo)));
  return new AdministracionClienteDtos.Pagina(r.getContent(),pagina,limite,r.getTotalElements(),r.getTotalPages());
 }
 /** Devuelve detalle si pertenece al taller deducido del servidor. */
 @Transactional(readOnly=true) public AdministracionClienteDtos.Detalle detalle(Long id,Long tallerId,Authentication a){Taller t=tallerPermitido(tallerId,a);return clientes.detallePorTaller(id,t.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Cliente no encontrado"));}
 /** Edita datos; el traslado de taller se permite exclusivamente al administrador. */
 @Transactional public AdministracionClienteDtos.Respuesta editar(Long id,AdministracionClienteDtos.Edicion d,MultipartFile foto,String key,Long tallerId,Authentication a)throws IOException{
  Taller alcance=tallerPermitido(tallerId,a); Cliente c=clientes.entidadPorTaller(id,alcance.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Cliente no encontrado")); if(key==null||key.isBlank())throw new IllegalArgumentException("Idempotency-Key es obligatorio");
  Taller destino=esAdmin(a)&&d.tallerId()!=null?tallerPermitido(d.tallerId(),a):alcance; validarEdicion(d,foto); duplicado(id,d); aplicar(c,d,destino); if(foto!=null&&!foto.isEmpty())c.fotografiaRuta=guardarFoto(foto); clientes.save(c);return new AdministracionClienteDtos.Respuesta(c.id,"Cliente actualizado",c.estatus);
 }
 /** Suspende sin borrar; la repetición es idempotente. */
 @Transactional public AdministracionClienteDtos.Respuesta suspender(Long id,Long tallerId,Authentication a){if(!esAdmin(a))throw new AccessDeniedException("Solo Administrador del Sistema puede suspender");Taller t=tallerPermitido(tallerId,a);Cliente c=clientes.entidadPorTaller(id,t.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Cliente no encontrado"));boolean ya=c.estatus==EstatusCliente.SUSPENDIDO;c.estatus=EstatusCliente.SUSPENDIDO;clientes.save(c);return new AdministracionClienteDtos.Respuesta(c.id,ya?"Cliente ya estaba suspendido":"Cliente suspendido",c.estatus);}
 /** Reactiva sin duplicar ni borrar; la repetición conserva el estado activo. */
 @Transactional public AdministracionClienteDtos.Respuesta reactivar(Long id,Long tallerId,Authentication a){if(!esAdmin(a))throw new AccessDeniedException("Solo Administrador del Sistema puede reactivar");Taller t=tallerPermitido(tallerId,a);Cliente c=clientes.entidadPorTaller(id,t.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND,"Cliente no encontrado"));boolean ya=c.estatus==EstatusCliente.ACTIVO;c.estatus=EstatusCliente.ACTIVO;clientes.save(c);return new AdministracionClienteDtos.Respuesta(c.id,ya?"Cliente ya estaba activo":"Cliente reactivado",c.estatus);}
 /** Lee una foto solo en el alcance permitido. */
 @Transactional(readOnly=true) public ClienteConsultaDtos.Foto fotografia(Long id,Long tallerId,Authentication a)throws IOException{Taller t=tallerPermitido(tallerId,a);String ruta=clientes.rutaFotoPorTaller(id,t.id).orElseThrow(()->new ResponseStatusException(HttpStatus.NOT_FOUND));Path f=Paths.get(ruta).toAbsolutePath().normalize(),root=uploads.toAbsolutePath().normalize();if(!Files.isRegularFile(f)||!f.startsWith(root))throw new ResponseStatusException(HttpStatus.NOT_FOUND);try(var in=ImageIO.createImageInputStream(f.toFile())){var readers=ImageIO.getImageReaders(in);if(!readers.hasNext())throw new ResponseStatusException(HttpStatus.NOT_FOUND);var reader=readers.next();try{reader.setInput(in);var out=new ByteArrayOutputStream();ImageIO.write(reader.read(0),"png",out);return new ClienteConsultaDtos.Foto(out.toByteArray(),"image/png");}finally{reader.dispose();}}}
 private void aplicar(Cliente c,Registro d,Taller t){c.taller=t;c.nombreCompleto=d.nombreCompleto().trim();c.contactoAlternativo=d.contactoAlternativo().trim();c.edad=d.edad();c.fechaNacimiento=d.fechaNacimiento();c.telefonoPersonal=d.telefonoPersonal().trim();c.telefonoTrabajo=d.telefonoTrabajo().trim();c.email=email(d.email());c.emailTrabajo=d.emailTrabajo()==null||d.emailTrabajo().isBlank()?null:email(d.emailTrabajo());c.calle=d.direccion().calle().trim();c.colonia=d.direccion().colonia().trim();c.municipio=d.direccion().municipio().trim();c.estado=d.direccion().estado().trim();c.codigoPostal=d.direccion().codigoPostal();}
 private void aplicar(Cliente c,AdministracionClienteDtos.Edicion d,Taller t){aplicar(c,new Registro(d.nombreCompleto(),d.contactoAlternativo(),d.edad(),d.fechaNacimiento(),d.telefonoPersonal(),d.telefonoTrabajo(),d.email(),d.emailTrabajo(),d.direccion(),t.id),t);}
 private void validar(Registro d,MultipartFile f,boolean requerida)throws IOException{if(Period.between(d.fechaNacimiento(),LocalDate.now()).getYears()!=d.edad())throw new IllegalArgumentException("La edad no coincide con la fecha de nacimiento");validarFoto(f,requerida);}
 private void validarEdicion(AdministracionClienteDtos.Edicion d,MultipartFile f)throws IOException{if(Period.between(d.fechaNacimiento(),LocalDate.now()).getYears()!=d.edad())throw new IllegalArgumentException("La edad no coincide con la fecha de nacimiento");validarFoto(f,false);}
 /** Valida MIME, límite y contenido binario de una imagen. */ public static void validarFoto(MultipartFile f,boolean requerida)throws IOException{if(f==null||f.isEmpty()){if(requerida)throw new IllegalArgumentException("La fotografía es obligatoria");return;}if(f.getSize()>15L*1024*1024||f.getContentType()==null||!f.getContentType().startsWith("image/"))throw new IllegalArgumentException("La fotografía debe ser una imagen válida de máximo 15 MB");try(InputStream in=f.getInputStream()){BufferedImage image=ImageIO.read(in);if(image==null)throw new IllegalArgumentException("El contenido de la fotografía no es una imagen válida");}}
 private String guardarFoto(MultipartFile f)throws IOException{Files.createDirectories(uploads);String n=UUID.randomUUID()+("image/png".equals(f.getContentType())?".png":".jpg");Files.copy(f.getInputStream(),uploads.resolve(n),StandardCopyOption.REPLACE_EXISTING);return uploads.resolve(n).toString();}
 private void duplicado(Long id,Registro d){if(id==null?clientes.existsByEmailOrTelefonoPersonalOrTelefonoTrabajoOrNombreCompletoAndFechaNacimiento(email(d.email()),d.telefonoPersonal().trim(),d.telefonoTrabajo().trim(),d.nombreCompleto().trim(),d.fechaNacimiento()):clientes.duplicadoExcluyendo(id,email(d.email()),d.telefonoPersonal().trim(),d.telefonoTrabajo().trim(),d.nombreCompleto().trim(),d.fechaNacimiento()))throw new IllegalArgumentException("Ya existe otro cliente con correo, teléfono o nombre y fecha de nacimiento coincidentes");}
 private void duplicado(Long id,AdministracionClienteDtos.Edicion d){if(clientes.duplicadoExcluyendo(id,email(d.email()),d.telefonoPersonal().trim(),d.telefonoTrabajo().trim(),d.nombreCompleto().trim(),d.fechaNacimiento()))throw new IllegalArgumentException("Ya existe otro cliente con correo, teléfono o nombre y fecha de nacimiento coincidentes");}
 private Taller tallerPermitido(Long solicitado,Authentication a){autorizar(a);if(esAdmin(a)){if(solicitado==null)throw new IllegalArgumentException("Selecciona un taller");return talleres.findById(solicitado).orElseThrow(()->new IllegalArgumentException("Taller inválido"));}User u=usuarios.findByEmail(a.getName()).orElseThrow(()->new AccessDeniedException("Usuario sin taller asignado"));if(u.taller==null)throw new AccessDeniedException("Usuario sin taller asignado");return u.taller;}
 private void autorizar(Authentication a){if(a==null||!a.isAuthenticated()||(!esAdmin(a)&&!tiene(a,RoleName.RECEPCIONISTA)))throw new AccessDeniedException("No tiene autorización para administrar clientes");} private boolean esAdmin(Authentication a){return tiene(a,RoleName.ADMINISTRADOR_SISTEMA);} private boolean tiene(Authentication a,RoleName r){return a!=null&&a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_"+r));}
 private String email(String v){return v.trim().toLowerCase(Locale.ROOT);} private String busqueda(String v){String x=v==null?"":v.strip();if(x.length()>120||x.chars().anyMatch(Character::isISOControl))throw new IllegalArgumentException("Búsqueda inválida");return x.toLowerCase(Locale.ROOT).replace("!","!!").replace("%","!%").replace("_","!_");}
}
