package com.taller.portal.service;
import com.taller.portal.dto.*; import com.taller.portal.dto.TallerDtos.*; import com.taller.portal.model.*; import com.taller.portal.repository.*; import java.io.*; import java.nio.file.*; import java.text.Normalizer; import java.time.*; import java.util.*; import org.springframework.data.domain.*; import org.springframework.security.access.AccessDeniedException; import org.springframework.security.core.Authentication; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional; import org.springframework.web.multipart.MultipartFile;
/** Fachada de talleres: única entrada que autoriza, valida RFC y evita duplicados. */
@Service public class TallerFacade {
 private static final String RFC="^[A-ZÑ&]{3,4}\\d{2}(0[1-9]|1[0-2])(0[1-9]|[12]\\d|3[01])[A-Z0-9]{2}[0-9A]$"; private final TallerRepository repo; private final UserRepository usuarios; private final Path uploads=Paths.get("uploads","talleres");
 /** @param repo repositorio de talleres @param usuarios alcance de recepción. */ public TallerFacade(TallerRepository repo,UserRepository usuarios){this.repo=repo;this.usuarios=usuarios;}
 /** Crea un taller para administrador y reutiliza validación de imagen. */ @Transactional public Respuesta crear(Registro d,MultipartFile foto,String key,Authentication a)throws IOException{admin(a);if(key==null||key.isBlank())throw new IllegalArgumentException("Idempotency-Key es obligatorio");var previo=repo.findByIdempotencyKey(key);if(previo.isPresent())return new Respuesta(previo.get().id,"Taller registrado");String rfc=rfc(d.rfc()),nombre=normalizar(d.nombre()),razon=normalizar(d.razonSocial());if(repo.existsByNombreNormalizadoOrRazonSocialNormalizada(nombre,razon)||repo.findByRfc(rfc).isPresent())throw new IllegalArgumentException("Ya existe un taller con RFC, nombre o razón social coincidente");ClienteRegistrationFacade.validarFoto(foto,false);Taller t=new Taller();t.nombre=d.nombre().trim();t.nombreNormalizado=nombre;t.razonSocial=d.razonSocial().trim();t.razonSocialNormalizada=razon;t.rfc=rfc;t.telefono=d.telefono();t.email=d.email().trim().toLowerCase(Locale.ROOT);t.calle=d.direccion().calle().trim();t.colonia=d.direccion().colonia().trim();t.municipio=d.direccion().municipio().trim();t.estado=d.direccion().estado().trim();t.codigoPostal=d.direccion().codigoPostal();t.idempotencyKey=key;if(foto!=null&&!foto.isEmpty())t.fotografiaRuta=guardar(foto);repo.save(t);return new Respuesta(t.id,"Taller registrado");}
 /** Lista todos para administrador o solo el taller asignado para recepción. */ @Transactional(readOnly=true) public Pagina listar(int pagina,int tamanio,Authentication a){if(a==null||!a.isAuthenticated())throw new AccessDeniedException("Acceso denegado");int limite=Math.min(Math.max(tamanio,1),10);if(esAdmin(a)){var r=repo.listar(PageRequest.of(Math.max(0,pagina),limite,Sort.by("nombre")));return new Pagina(r.getContent(),pagina,limite,r.getTotalElements(),r.getTotalPages());}User u=usuarios.findByEmail(a.getName()).orElseThrow(()->new AccessDeniedException("Usuario sin taller asignado"));if(u.taller==null)throw new AccessDeniedException("Usuario sin taller asignado");var x=repo.resumen(u.taller.id).orElseThrow();return new Pagina(List.of(x),0,1,1,1);}
 /** Valida RFC mexicano, incluyendo fecha de calendario. */ public static String rfc(String v){String x=v==null?"":v.replaceAll("\\s+","").toUpperCase(Locale.ROOT);if(!x.matches(RFC))throw new IllegalArgumentException("RFC inválido");int inicio=x.length()==12?3:4;try{LocalDate.of(2000+Integer.parseInt(x.substring(inicio,inicio+2)),Integer.parseInt(x.substring(inicio+2,inicio+4)),Integer.parseInt(x.substring(inicio+4,inicio+6)));}catch(DateTimeException e){throw new IllegalArgumentException("La fecha del RFC no es válida");}return x;}
 private String normalizar(String v){return Normalizer.normalize(v.trim(),Normalizer.Form.NFD).replaceAll("\\p{M}","").toUpperCase(Locale.ROOT).replaceAll("\\s+"," ");}
 private String guardar(MultipartFile f)throws IOException{Files.createDirectories(uploads);String n=UUID.randomUUID()+("image/png".equals(f.getContentType())?".png":".jpg");Files.copy(f.getInputStream(),uploads.resolve(n),StandardCopyOption.REPLACE_EXISTING);return uploads.resolve(n).toString();}
 private void admin(Authentication a){if(!esAdmin(a))throw new AccessDeniedException("Solo Administrador del Sistema puede crear talleres");} private boolean esAdmin(Authentication a){return a!=null&&a.isAuthenticated()&&a.getAuthorities().stream().anyMatch(x->x.getAuthority().equals("ROLE_"+RoleName.ADMINISTRADOR_SISTEMA));}
}
