import { useEffect, useState } from 'react';
import { LoaderCircle, MapPin } from 'lucide-react';

/** Consulta exclusivamente la API local autenticada. @param {string} ruta endpoint local @param {AbortSignal} signal cancelación. @returns {Promise<unknown>} JSON. */
async function consultarCatalogo(ruta, signal) {
  const response = await fetch(ruta, { signal, headers: { Authorization: `Bearer ${localStorage.getItem('taller_token')}` } });
  if (response.status === 404) return null;
  if (!response.ok) throw new Error(response.status === 403 ? 'No tienes permiso para usar el catálogo postal.' : 'El catálogo local no está disponible.');
  return response.json();
}

/** Autocompleta por CP o cascada local, manteniendo siempre captura manual. @param {{values:object,setValues:Function}} props estado del registro. @returns {JSX.Element} campos de dirección. */
export default function DireccionAutocompletada({ values, setValues }) {
  const [estados, setEstados] = useState([]); const [municipios, setMunicipios] = useState([]); const [colonias, setColonias] = useState([]);
  const [cargando, setCargando] = useState(false); const [aviso, setAviso] = useState('');
  /** Fusiona solo propiedades de dirección. @param {object} cambio valores nuevos. @returns {void}. */
  const actualizar = cambio => setValues(anterior => ({ ...anterior, ...cambio }));
  useEffect(() => { const controller = new AbortController(); setCargando(true); async function cargar() { try { const datos = await consultarCatalogo('/api/codigos-postales/estados', controller.signal); if (!controller.signal.aborted) { setEstados(datos || []); if (!datos?.length) setAviso('El catálogo local aún no tiene datos. Puedes capturar la dirección manualmente.'); } } catch (error) { if (!controller.signal.aborted) setAviso(error.message); } finally { if (!controller.signal.aborted) setCargando(false); } } cargar(); return () => controller.abort(); }, []);
  useEffect(() => { if (!/^\d{5}$/.test(values.codigoPostal)) return undefined; const controller = new AbortController(); const espera = setTimeout(async () => { setCargando(true); setAviso(''); try { const datos = await consultarCatalogo(`/api/codigos-postales/${values.codigoPostal}`, controller.signal); if (!controller.signal.aborted) { if (!datos) { setColonias([]); setAviso('No encontramos ese código postal en el catálogo local. Puedes continuar manualmente.'); return; } setColonias(datos.colonias || []); actualizar({ estado: datos.estado, municipio: datos.municipio, colonia: '' }); } } catch (error) { if (!controller.signal.aborted) setAviso(error.message); } finally { if (!controller.signal.aborted) setCargando(false); } }, 300); return () => { clearTimeout(espera); controller.abort(); }; }, [values.codigoPostal]);
  useEffect(() => { if (!values.estado || /^\d{5}$/.test(values.codigoPostal)) return undefined; const controller = new AbortController(); const espera = setTimeout(async () => { setCargando(true); try { const datos = await consultarCatalogo(`/api/codigos-postales/municipios?estado=${encodeURIComponent(values.estado)}`, controller.signal); if (!controller.signal.aborted) { setMunicipios(datos || []); if (!datos?.length) setAviso('No hay municipios para ese estado en el catálogo local. Puedes continuar manualmente.'); } } catch (error) { if (!controller.signal.aborted) setAviso(error.message); } finally { if (!controller.signal.aborted) setCargando(false); } }, 300); return () => { clearTimeout(espera); controller.abort(); }; }, [values.estado, values.codigoPostal]);
  useEffect(() => { if (!values.estado || !values.municipio || /^\d{5}$/.test(values.codigoPostal)) return undefined; const controller = new AbortController(); const espera = setTimeout(async () => { setCargando(true); try { const datos = await consultarCatalogo(`/api/codigos-postales/colonias?estado=${encodeURIComponent(values.estado)}&municipio=${encodeURIComponent(values.municipio)}`, controller.signal); if (!controller.signal.aborted) { setColonias(datos || []); if (!datos?.length) setAviso('No hay colonias para esa combinación. Puedes continuar manualmente.'); } } catch (error) { if (!controller.signal.aborted) setAviso(error.message); } finally { if (!controller.signal.aborted) setCargando(false); } }, 300); return () => { clearTimeout(espera); controller.abort(); }; }, [values.estado, values.municipio, values.codigoPostal]);
  /** Cambia CP, conserva dígitos y limpia dependientes. @param {Event} event input. @returns {void}. */
  function cambiarCodigoPostal(event) { const codigoPostal = event.target.value.replace(/\D/g, '').slice(0, 5); actualizar({ codigoPostal, estado: '', municipio: '', colonia: '' }); setMunicipios([]); setColonias([]); setAviso(''); }
  /** Cambia estado y limpia cascada. @param {Event} event input. @returns {void}. */
  function cambiarEstado(event) { actualizar({ estado: event.target.value, municipio: '', colonia: '', codigoPostal: '' }); setMunicipios([]); setColonias([]); setAviso(''); }
  /** Cambia municipio y limpia sus dependientes. @param {Event} event input. @returns {void}. */
  function cambiarMunicipio(event) { actualizar({ municipio: event.target.value, colonia: '', codigoPostal: '' }); setColonias([]); setAviso(''); }
  /** Cambia colonia y completa CP al elegir una sugerencia. @param {Event} event input. @returns {void}. */
  function cambiarColonia(event) { const colonia = event.target.value; const opcion = colonias.find(item => item.colonia === colonia); actualizar({ colonia, codigoPostal: opcion ? opcion.codigoPostal : values.codigoPostal }); }
  /** Muestra texto libre con datalist local. @param {{id:string,label:string,value:string,onChange:Function,list:string,options:string[]}} props control. @returns {JSX.Element} input. */
  function CampoLista({ id, label, value, onChange, list, options }) { return <div className="form-field"><label htmlFor={id}>{label}</label><div className="input-control"><MapPin className="input-icon" size={18} aria-hidden="true"/><input id={id} name={id} value={value} onChange={onChange} list={list} maxLength="120" required aria-describedby={`${id}-hint`} /></div><datalist id={list}>{options.map((opcion, indice) => <option key={`${opcion}-${indice}`} value={opcion} />)}</datalist><small id={`${id}-hint`} className="field-hint">Puedes escribir una corrección manual.</small></div>; }
  return <div className="field-grid direccion-catalogo" aria-busy={cargando}>
    <div className="form-field"><label htmlFor="calle">Calle</label><div className="input-control"><MapPin className="input-icon" size={18} aria-hidden="true"/><input id="calle" name="calle" value={values.calle} onChange={event => actualizar({ calle: event.target.value })} maxLength="120" required /></div></div>
    <div className="form-field"><label htmlFor="codigoPostal">Código postal</label><div className="input-control"><MapPin className="input-icon" size={18} aria-hidden="true"/><input id="codigoPostal" name="codigoPostal" value={values.codigoPostal} onChange={cambiarCodigoPostal} inputMode="numeric" pattern="[0-9]{5}" maxLength="5" required aria-describedby="codigoPostal-hint" /></div><small id="codigoPostal-hint" className="field-hint">Escribe 5 dígitos para autocompletar localmente.</small></div>
    <CampoLista id="estado" label="Estado" value={values.estado} onChange={cambiarEstado} list="estados-locales" options={estados}/><CampoLista id="municipio" label="Municipio" value={values.municipio} onChange={cambiarMunicipio} list="municipios-locales" options={municipios}/><CampoLista id="colonia" label="Colonia" value={values.colonia} onChange={cambiarColonia} list="colonias-locales" options={colonias.map(item => item.colonia)}/>
    {cargando && <p className="catalogo-status" role="status"><LoaderCircle size={16} className="catalogo-spinner"/>Consultando catálogo local…</p>}{aviso && <p className="catalogo-status catalogo-warning" role="status">{aviso}</p>}
  </div>;
}
