import React, { useEffect, useState } from 'react';
import { ArrowLeft, Building2, Plus } from 'lucide-react';
import DireccionAutocompletada from './DireccionAutocompletada';

/** Gestiona alta y listado paginado de talleres para Administrador. @param {{volver:Function}} props retorno. @returns {JSX.Element} vista de talleres. */
export default function Talleres({ volver }) {
  const [items, setItems] = useState([]); const [form, setForm] = useState({ nombre:'', razonSocial:'', rfc:'', telefono:'', email:'', calle:'', colonia:'', municipio:'', estado:'', codigoPostal:'' });
  const [foto,setFoto]=useState(null); const [cargando,setCargando]=useState(true); const [guardando,setGuardando]=useState(false); const [mensaje,setMensaje]=useState('');
  /** Valida preventivamente el archivo sin sustituir la validación del servidor. @param {Event} evento de selector. @returns {void}. */
  function seleccionarFoto(e){const archivo=e.target.files[0];if(!archivo){setFoto(null);return;}if(!archivo.type.startsWith('image/')||archivo.size>15*1024*1024){setFoto(null);setMensaje('La fotografía debe ser una imagen válida de máximo 15 MB.');e.target.value='';return;}setFoto(archivo);}
  /** Carga talleres autorizados. @returns {Promise<void>} actualiza el listado. */
  async function cargar(){setCargando(true);try{const r=await fetch('/api/talleres?pagina=0&tamanio=10',{headers:{Authorization:`Bearer ${localStorage.getItem('taller_token')}`}});const d=await r.json();if(!r.ok)throw Error(d.message||'No se pudieron cargar talleres.');setItems(d.talleres||[]);}catch(e){setMensaje(e.message);}finally{setCargando(false);}}
  useEffect(()=>{cargar();},[]);
  /** Envía un taller idempotente. @param {Event} e envío. @returns {Promise<void>}. */
  async function guardar(e){e.preventDefault();setGuardando(true);setMensaje('');try{const d=new FormData();d.append('datos',new Blob([JSON.stringify({nombre:form.nombre,razonSocial:form.razonSocial,rfc:form.rfc,telefono:form.telefono,email:form.email,direccion:{calle:form.calle,colonia:form.colonia,municipio:form.municipio,estado:form.estado,codigoPostal:form.codigoPostal}})],{type:'application/json'}));if(foto)d.append('fotografia',foto);const r=await fetch('/api/talleres',{method:'POST',headers:{Authorization:`Bearer ${localStorage.getItem('taller_token')}`,'Idempotency-Key':crypto.randomUUID()},body:d});const x=await r.json();if(!r.ok)throw Error(x.message||'No se pudo crear el taller.');setMensaje('Taller registrado');setForm({nombre:'',razonSocial:'',rfc:'',telefono:'',email:'',calle:'',colonia:'',municipio:'',estado:'',codigoPostal:''});setFoto(null);cargar();}catch(x){setMensaje(x.message);}finally{setGuardando(false);}}
  return <main className="registration-page"><div className="registration-shell"><button className="text-button back-button" onClick={volver}><ArrowLeft size={18}/>Volver al panel</button><section className="registration-card"><header className="form-heading"><p className="eyebrow">Administración</p><h1>Talleres</h1><p>Crea y consulta los talleres de la empresa.</p></header>{mensaje&&<div className={`notice ${mensaje==='Taller registrado'?'notice-success':'notice-error'}`} role="status">{mensaje}</div>}<form onSubmit={guardar}><fieldset><legend><Building2 size={17}/>Datos del taller</legend><div className="field-grid">{[['nombre','Nombre del taller','text'],['razonSocial','Razón social','text'],['rfc','RFC','text'],['telefono','Teléfono del taller','tel'],['email','E-mail de contacto','email']].map(([id,label,type])=><div className="form-field" key={id}><label htmlFor={`t-${id}`}>{label}</label><div className="input-control"><input id={`t-${id}`} value={form[id]} type={type} required maxLength={id==='rfc'?13:160} pattern={id==='telefono'?'[0-9]{10}':undefined} onChange={e=>setForm({...form,[id]:e.target.value})}/></div></div>)}</div></fieldset><fieldset><legend>Dirección</legend><DireccionAutocompletada values={form} setValues={setForm}/></fieldset><fieldset><legend>Fotografía opcional</legend><div className="form-field"><label htmlFor="foto-taller">Imagen del negocio (máx. 15 MB)</label><input id="foto-taller" type="file" accept="image/*" onChange={seleccionarFoto}/></div></fieldset><button className="primary-button submit-button" disabled={guardando}>{guardando?'Guardando…':<><Plus size={18}/>Crear taller</>}</button></form><section className="consulta-card"><h2>Talleres registrados</h2>{cargando?<p className="consulta-loading">Cargando…</p>:<ul className="taller-list">{items.map(x=><li key={x.id}><strong>{x.nombre}</strong><span>{x.razonSocial} · {x.municipio}</span></li>)}</ul>}</section></section></div></main>;
}
